cmd_/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o := aarch64-linux-gnu-gcc -Wp,-MD,/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /home/arron/sdk/s802/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux/bin/../lib/gcc/aarch64-linux-gnu/4.9.2/include -I/home/work/xiezx/git/common/arch/arm64/include -Iarch/arm64/include/generated  -I/home/work/xiezx/git/common/include -Iinclude -I/home/work/xiezx/git/common/arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I/home/work/xiezx/git/common/include/uapi -Iinclude/generated/uapi -include /home/work/xiezx/git/common/include/linux/kconfig.h   -I/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601 -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Werror -Wno-error=cpp -O2 -mgeneral-regs-only -fno-pic -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO   -I/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/include -DANDROID_SUPPORT -DPBF_MONITOR_SUPPORT -DCONFIG_LITTLE_ENDIAN -DUSB_BULK_BUF_ALIGMENT -DUSB_BULK_BUF_PREALLOC -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -DCE_BBP_NOISE_ENDURANCE_SUPPORT -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DADHOC_WPA2PSK_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDYNAMIC_PD_SUPPORT -DCONFIG_P2P_AUTO_GO_AS_SOFTAP -DDOT11_N_SUPPORT -DP2P_SUPPORT -DAPCLI_SUPPORT -DMAT_SUPPORT -DAP_SCAN_SUPPORT -DSCAN_SUPPORT -DP2P_APCLI_SUPPORT -DCONFIG_AP_SUPPORT -DCONFIG_APSTA_MIXED_SUPPORT -DUAPSD_SUPPORT -DMBSS_SUPPORT -DIAPP_SUPPORT -DDOT1X_SUPPORT -DWSC_AP_SUPPORT -DWSC_STA_SUPPORT -DSTATS_COUNT_SUPPORT -DRT_CFG80211_SUPPORT -DEXT_BUILD_CHANNEL_LIST -DLED_CONTROL_SUPPORT -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT  -DMODULE    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601usta)" -c -o /home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o /home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.c

source_/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o := /home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.c

deps_/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \
    $(wildcard include/config/ap/support.h) \

/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o: $(deps_/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o)

$(deps_/home/work/xiezx/git/hardware/wifi/mtk/drivers/mt7601/rate_ctrl/alg_ags.o):
